spring:
  application:
    name: admin
server:
  port: 8000
#dubbo:
#  registry:
#    address: zookeeper://127.0.0.1:2181
#    protocol: zookeeper
#  protocol:
#    port: -1

# 直连方式
#dubbo:
#  protocol:
#    name: dubbo
#    port: 20888

tapestry:
  integration:
    appmodule: org.example.tapestry.admin.services.AppModule
  production-mode: false